

server:
  port: 8083

spring:
  application:
    name: common-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/


zuul:
  routes:
    microservice-user: /microservice-user/**
